import numpy as np
import pandas as pd

from traffic_forecasting.config import (
    DATETIME_COLUMN,
    LAG_HOURS,
    ROLLING_WINDOWS,
    TARGET_COLUMN,
)

# Weather-related columns in the dataset, categorized by data type for processing.
WEATHER_NUMERIC_COLUMNS = ("temp", "rain_1h", "snow_1h", "clouds_all")
WEATHER_CATEGORICAL_COLUMNS = ("weather_main", "weather_description")

# Time constants for feature engineering
HOURS_PER_DAY = 24
DAYS_PER_WEEK = 7
MONTHS_PER_YEAR = 12
WEEKEND_DAYS = (5, 6)

# Offset to convert temperature from Kelvin to Celsius.
KELVIN_TO_CELSIUS_OFFSET = 273.15

LAG_FEATURE_COLUMNS = tuple(f"{TARGET_COLUMN}_lag_{lag_hours}" for lag_hours in LAG_HOURS)
ROLLING_FEATURE_COLUMNS = tuple(
    feature_name
    for window in ROLLING_WINDOWS
    for feature_name in (
        f"{TARGET_COLUMN}_rolling_mean_{window}",
        f"{TARGET_COLUMN}_rolling_std_{window}",
    )
)
HISTORICAL_FEATURE_COLUMNS = (*LAG_FEATURE_COLUMNS, *ROLLING_FEATURE_COLUMNS)


def get_feature_groups() -> dict[str, tuple[str, ...]]:
    """Return feature groups generated by the feature engineering module."""
    return {
        "temporal": (
            "hour",
            "day_of_week",
            "month",
        ),
        "calendar": (
            "is_weekend",
            "is_holiday",
        ),
        "cyclical": (
            "hour_sin",
            "hour_cos",
            "day_of_week_sin",
            "day_of_week_cos",
            "month_sin",
            "month_cos",
        ),
        "weather_numeric": (
            *WEATHER_NUMERIC_COLUMNS,
            "temp_celsius",
        ),
        "weather_categorical": WEATHER_CATEGORICAL_COLUMNS,
        "lag": LAG_FEATURE_COLUMNS,
        "rolling": ROLLING_FEATURE_COLUMNS,
    }


def add_time_features(data: pd.DataFrame) -> pd.DataFrame:
    """Add numeric time components derived from the observation timestamp."""
    result = data.copy()
    result["hour"] = result[DATETIME_COLUMN].dt.hour
    result["day_of_week"] = result[DATETIME_COLUMN].dt.dayofweek
    result["month"] = result[DATETIME_COLUMN].dt.month
    return result


def add_calendar_features(data: pd.DataFrame) -> pd.DataFrame:
    """Add weekend and holiday indicator features."""
    result = data.copy()
    result["is_weekend"] = result["day_of_week"].isin(WEEKEND_DAYS).astype("int8")
    holiday_values = result["holiday"].astype("string").str.strip()
    result["is_holiday"] = (holiday_values.notna() & holiday_values.ne("")).astype("int8")
    return result


def add_cyclical_features(data: pd.DataFrame) -> pd.DataFrame:
    """Encode periodic calendar components with sine and cosine pairs."""
    result = data.copy()
    result["hour_sin"] = np.sin(2 * np.pi * result["hour"] / HOURS_PER_DAY)
    result["hour_cos"] = np.cos(2 * np.pi * result["hour"] / HOURS_PER_DAY)
    result["day_of_week_sin"] = np.sin(2 * np.pi * result["day_of_week"] / DAYS_PER_WEEK)
    result["day_of_week_cos"] = np.cos(2 * np.pi * result["day_of_week"] / DAYS_PER_WEEK)
    # Month is shifted so January starts at the beginning of the annual cycle.
    month_position = result["month"] - 1
    result["month_sin"] = np.sin(2 * np.pi * month_position / MONTHS_PER_YEAR)
    result["month_cos"] = np.cos(2 * np.pi * month_position / MONTHS_PER_YEAR)
    return result


def add_weather_features(data: pd.DataFrame) -> pd.DataFrame:
    """Preserve weather columns and add temperature in degrees Celsius."""
    result = data.copy()
    result["temp_celsius"] = result["temp"] - KELVIN_TO_CELSIUS_OFFSET
    return result


def add_lag_features(data: pd.DataFrame) -> pd.DataFrame:
    """Add historical traffic values at configured hourly offsets."""
    result = data.copy()
    for lag_hours, column in zip(
        LAG_HOURS,
        LAG_FEATURE_COLUMNS,
        strict=True,
    ):
        result[column] = result[TARGET_COLUMN].shift(lag_hours)
    return result


def add_rolling_features(data: pd.DataFrame) -> pd.DataFrame:
    """Add rolling traffic statistics calculated from past values only."""
    result = data.copy()
    # Shift first to exclude the current target value from rolling statistics.
    past_target = result[TARGET_COLUMN].shift(1)

    for window in ROLLING_WINDOWS:
        rolling_window = past_target.rolling(window=window)
        result[f"{TARGET_COLUMN}_rolling_mean_{window}"] = rolling_window.mean()
        # Use population standard deviation (ddof=0) to avoid NaN values for small windows.
        result[f"{TARGET_COLUMN}_rolling_std_{window}"] = rolling_window.std(ddof=0)

    return result


def drop_incomplete_feature_rows(data: pd.DataFrame) -> pd.DataFrame:
    """Remove rows without a target or complete historical feature values."""
    # Drop technical gaps only after all historical features have been created.
    required_columns = [TARGET_COLUMN, *HISTORICAL_FEATURE_COLUMNS]
    return data.dropna(subset=required_columns).sort_values(DATETIME_COLUMN).reset_index(drop=True)


def build_feature_dataset(data: pd.DataFrame) -> pd.DataFrame:
    """Build the complete feature dataset while preserving chronology."""
    result = data.sort_values(DATETIME_COLUMN).reset_index(drop=True).copy()
    result = add_time_features(result)
    result = add_calendar_features(result)
    result = add_cyclical_features(result)
    result = add_weather_features(result)
    result = add_lag_features(result)
    result = add_rolling_features(result)
    return drop_incomplete_feature_rows(result)
